#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "p_info.h"

int
worker_process_global_css(CONTAINER_WORKER *me, CONTAINER_REQUEST *req)
{
	(void) me;
	
	req->api->header(req, "Content-type", "text/css", 1);
	req->api->puts(req, 
	"/*\n"
	"Copyright (c) 2010, Yahoo! Inc. All rights reserved.\n"
	"Code licensed under the BSD License:\n"
	"http://developer.yahoo.com/yui/license.html\n"
	"version: 3.2.0\n"
	"build: 2676\n"
	"*/\n"
	"html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}\n"
	"body{font:13px/1.231 'Helvetica Neue',arial,helvetica,clean,sans-serif;*font-size:small;*font:x-small;}select,input,button,textarea{font:99% arial,helvetica,clean,sans-serif;}table{font-size:inherit;font:100%;}pre,code,kbd,samp,tt{font-family:monospace;*font-size:108%;line-height:100%;}\n"
	"\n"
	"em, i { font-style: italic; }\n"
	"strong, b { font-weight: bold; }\n"
	"a { text-decoration: none; color: #007; }\n"
	"a:hover, a:active { text-decoration: underline; }\n"
	"\n"
	"header, article, footer {\n"
	"	display: block;\n"
	"	width: 976px;\n"
	"	margin: 1em auto;\n"
	"}\n"
	"header {\n"
	"	margin: 0 auto 16px auto;\n"
	"	border-bottom: solid #ccc 1px;\n"
	"	padding: 8px 0;\n"
	"}\n"
	"header p, header ul, header ul>li {\n"
	"	display: inline;\n"
	"	color: #666;\n"
	"	margin: 0;\n"
	"}\n"
	"header li:after {\n"
	"	content: ', ';\n"
	"}\n"
	"header li:last-child:after {\n"
	"	content: '.';\n"
	"}\n"
	"footer {\n"
	"    margin: 16px auto 0 auto;\n"
	"    border-top: solid #ccc 1px;\n"
	"    font-family: 'Gill Sans', 'Arial';\n"
	"	padding-top: 8px;\n"
	"	color: #666;\n"
	"	min-height: 48px;\n"
	"}\n"
	"footer strong {\n"
	"	color: #000;\n"
	"}\n"
	"h1 {\n"
	"	font-family: 'Gill Sans';\n"
	"	font-size: 150%;\n"
	"}\n"
	"table, td, th {\n"
	"	font-size: 100%;\n"
	"}\n"
	"\n"
	"table {\n"
	"	border-collapse: collapse;\n"
	"	margin: 1em 0 1em 0;\n"
	"	border: solid #666 1px;\n"
	"	table-layout: fixed;\n"
	"	width: 100%;\n"
	"}\n"
	"th, td {\n"
	"	padding: 6px;\n"
	"	vertical-align: top;\n"
	"}\n"
	"thead, th {\n"
	"	background: #666;\n"
	"	color: #fff;\n"
	"	border: solid #666 1px;\n"
	"}\n"
	"thead th {\n"
	"	font-weight: normal;\n"
	"	padding: 6px 4px;\n"
	"}\n"
	"thead th.predicate {\n"
	"	width: 14em;\n"
	"}\n"
	"td {\n"
	"	vertical-align: top;\n"
	"	padding: 4px;\n"
	"	border: solid #666 1px;\n"
	"	word-wrap: break-word;\n"
	"}\n"
	"thead {\n"
	"	padding-right: 8px;\n"
	"}\n"
	"table > tbody > tr > th {\n"
	"	width: 12em;\n"
	"	word-wrap: break-word;\n"
	"}\n"
	"td p {\n"
	"	margin: 0 0 0.5em 0;\n"
	"}\n"
	"q {\n"
	"	color: #700;\n"
	"}\n"
	"p, ul, dl, dt {\n"
	"	margin: 1em 0;\n"
	"}\n"
	"dl>dd, ul>li {\n"
	"	display: list-item;\n"
	"	margin: 0.25em 0 0.25em 1.5em;\n"
	"	list-style: square outside;\n"
	"}\n"
	"article.photo img {\n"
	"	display: block;\n"
	"	max-width: 100%;\n"
	"	margin: 0 auto;\n"
	"}\n"
	"article h2 {\n"
	"	font-size: 150%;\n"
	"    font-family: 'Gill Sans', 'Arial';\n"
	"	margin: 12px 0;\n"
	"}\n"
	"article h3 {\n"
	"	font-size: 140%;\n"
	"    font-family: 'Gill Sans', 'Arial';\n"
	"	margin: 12px 0;\n"
	"	color: #666;\n"
	"}\n"
	"pre {\n"
	"	background: #eee;\n"
	"	border: solid #666 1px;\n"
	"	padding: 12px;\n"
	"}\n"
	"section.metadata {\n"
	"	width: 48%;\n"
	"	margin: 4px;\n"
	"	float: left;\n"
	"}\n"
	".clear {\n"
	"	display: block;\n"
	"	height: 1px;\n"
	"	clear: both;\n"
	"}\n"
	"form {\n"
	"	display: block;\n"
	"	padding: 12px;\n"
	"}\n"
	"form label {\n"
	"	display: block;\n"
	"	font-weight: bold;\n"
	"	margin: 0.25em 0;\n"
	"}\n"
	"section.form {\n"
	"	border-bottom: solid #ccc 1px;\n"
	"	margin-bottom: 12px;\n"
	"	padding-bottom: 18px;\n"
	"}\n");
	return 0;
}